### ISSUE TITLE
AttributeError: 'WebDriver' object has no attribute 'find_element_by_ ...

### ISSUE THREAD

**Issue by nlublovary** [MetaProvide/talked#49]
### General Description

The syntax "find_element_by_ ... " throws an AttributeError with the latest version of Selenium, because that syntax is deprecated

`find_element_by_css_selector(` has to be replaced with `find_element(By.CSS_SELECTOR,`
`find_element_by_tag_name(` has to be replaced with `find_element(By.TAG_NAME,`

more on https://selenium-python.readthedocs.io/locating-elements.html

### How To Reproduce?

1. Install latest version of everything as of Sep 15, 2022
2. /recording start
3. wait until error appears in the log

### Screenshots

![gzhKLSYZYs](https://user-images.githubusercontent.com/7830031/190345501-01b40713-05ce-4026-b337-2e434fa121de.png)

### Operating System

Ubuntu 22.04.1 LTS, python 3.10, selenium 4.4.3

### Logs

```
File "/opt/talked/talked/lib/python3.10/site-packages/talked/recorder.py", line 208, in change_name_of_user
    driver.find_element_by_css_selector("input.username-form__input").send_keys(
AttributeError: 'WebDriver' object has no attribute 'find_element_by_css_selector'
```

### Talked Version

Talked client version: [e.g. 0.4.0]
Talked server version: [e.g. 0.4.0]

**Comment by mwalbeck** [comment]
Thanks for reporting!

Should be fixed in 0.4.1
